# theme: minima
remote_theme: pages-themes/midnight@v0.2.0
title: Open Source @ UNA
description: Reposotiorio Open Source de documentación en nuevas tecnologías
site:
   github:
      repository_url: https://github.com/tfg2021-escinf-una/tfg2021-escinf-una.github.io
navigation:
  - title: Home
    url: /
  - title: About Us
    url: about
baseurl: "/"
url: "localhost:4000"
plugins:
  - jekyll-remote-theme
  - jemoji