# theme: minima
remote_theme: pages-themes/cayman@v0.2.0
title: Open Source @ UNA
description: Reposotiorio Open Source de documentación en nuevas tecnologías
navigation:
  - title: Home
    url: /
  - title: About Us
    url: about
baseurl: "/"
url: "localhost:4000"
plugins:
  - jekyll-remote-theme
  - jemoji