# theme: minima
remote_theme: pages-themes/cayman@v0.2.0
title: Microservicios, CI/CD, DevOps y OpenSource
description: Sitio web explicativo basado en temas de Microservicios, CI/CD, DevOps y OpenSource
navigation:
  - title: Home
    url: /
  - title: About Us
    url: about
baseurl: "/"
url: "localhost:4000"
plugins:
  - jekyll-remote-theme